### ISSUE TITLE
Error parsing install.rdf: "RDF/XML syntax error: No namespace for about in "

### ISSUE THREAD

**Issue by muffinresearch** [rdf-ext/rdf-parser-rdfxml#1]
Hi, I'm trying to use rdf-parser-rdfxml to parse install.rdf for a mozilla addon but the parser seems to blow up on the unqualified about attribute.

This is the line I'm hitting: https://github.com/rdf-ext/rdf-parser-rdfxml/blob/master/index.js#L259

According to the spec [1] specific local-names including about should be allowed to be unqualified.

> If ·namespace-name· is present, set to a string value of the concatenation of the value of the ·namespace-name· accessor and the value of the ·local-name· accessor. Otherwise if ·local-name· is ID, about, resource, parseType or type, set to a string value of the concatenation of the ·RDF namespace URI reference· and the value of the ·local-name· accessor. Other non-namespaced ·local-name· accessor values are forbidden.

[1] https://www.w3.org/TR/REC-rdf-syntax/#eventterm-attribute-URI 

Here's an example install.rdf for testing purposes:

``` xml
<?xml version="1.0"?>

<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:em="http://www.mozilla.org/2004/em-rdf#">

  <Description about="urn:mozilla:install-manifest">
  <em:id>{Themes_UUID}</em:id>
    <em:version>Themes_Version</em:version>

<!-- Target Application this extension can install into,
         with minimum and maximum supported versions. -->

<em:targetApplication>
    <Description>
      <!-- Firefox's UUID -->
      <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
      <em:minVersion>Min_FF_Version</em:minVersion>
      <em:maxVersion>Max_FF_Version</em:maxVersion>
    </Description>
  </em:targetApplication>

  <!-- Front End MetaData -->
  <!-- My_Theme -->
  <em:name>My_Theme</em:name>
  <em:description>My_Theme</em:description>
  <em:creator>Your_Name</em:creator>
  <em:contributor>Contributors_Names</em:contributor>
  <em:homepageURL>Themes_HomePage</em:homepageURL>
  <em:updateURL> Url_of_Update_Location </em:updateURL>
  <em:aboutURL> Url_of_About_Page </em:aboutURL>

  <!-- Front End Integration Hooks (used by Theme Manager)-->
    <em:internalName>My_Theme</em:internalName>
  </Description>

</RDF>
```

**Comment by muffinresearch** [comment]
Here's a very cursory testcase + patch. https://github.com/muffinresearch/rdf-parser-rdfxml/commit/327db6108fb1743f12431bd52306a5952b829e94

Note it doesn't handle duplicates as mentioned here [1]:

> The construction of RDF URI references from XML attributes can generate the same RDF URI references from different XML attributes. This can cause ambiguity in the grammar when matching attribute events (such as when rdf:about and about XML attributes are both present). Documents that have this are illegal. 

[1] https://www.w3.org/TR/REC-rdf-syntax/#eventterm-attribute-URI

**Comment by muffinresearch** [comment]
This patch doesn't appear to be enough. With the patch above all the subjects for the install.rdf example  are a blank node. 

The problem is in this line - https://github.com/rdf-ext/rdf-parser-rdfxml/blob/master/index.js#L296

`about` is looked up with the expectation it is namespaced and in this case since it isn't it defaults to a blank node. `ID` would need to be dealt with in a similar way too.

**Comment by bergos** [comment]
@muffinresearch The problem should be solved with this [PR](https://github.com/rdf-ext/rdf-parser-rdfxml/pull/2).

@timbl This parsers uses rdflib.js code. So this patch should be also added to rdflib.js.

**Comment by bergos** [comment]
@muffinresearch npm version 0.3.1 contains the fix.

**Comment by muffinresearch** [comment]
@bergos thanks!
